# Generated by Django 3.2.9 on 2021-12-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('ingredients', models.TextField(verbose_name='Пароль')),
                ('cooking_time', models.IntegerField(verbose_name='Стоимость')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блюда',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('type', models.CharField(max_length=50, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Официант',
                'verbose_name_plural': 'Официанты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Вид заказа')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dishes')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.payment')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.waiter')),
            ],
            options={
                'verbose_name': 'Заказщик',
                'verbose_name_plural': 'Заказщики',
            },
        ),
    ]
